"""add inventory items and currency to character

Revision ID: f12a04ae8917
Revises: c8d4f2a91e3b
Create Date: 2026-07-27 19:06:01.154156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f12a04ae8917'
down_revision: Union[str, Sequence[str], None] = 'c8d4f2a91e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item',
    sa.Column('name', sqlmodel.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.AutoString(), nullable=False),
    sa.Column('subtitle', sqlmodel.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_equippable', sa.Boolean(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('equip_slot', sqlmodel.AutoString(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('character', sa.Column('copper_pieces', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('character', sa.Column('silver_pieces', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('character', sa.Column('gold_pieces', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('character', sa.Column('platinum_pieces', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('character', 'copper_pieces', server_default=None)
    op.alter_column('character', 'silver_pieces', server_default=None)
    op.alter_column('character', 'gold_pieces', server_default=None)
    op.alter_column('character', 'platinum_pieces', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'platinum_pieces')
    op.drop_column('character', 'gold_pieces')
    op.drop_column('character', 'silver_pieces')
    op.drop_column('character', 'copper_pieces')
    op.drop_table('inventory_item')
    # ### end Alembic commands ###
