"""add character, class and race tables

Revision ID: f26112316832
Revises: 
Create Date: 2026-07-17 19:38:19.279906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f26112316832'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('BARBARIAN', 'BARD', 'CLERIC', 'DRUID', 'FIGHTER', 'MONK', 'PALADIN', 'RANGER', 'ROGUE', 'SORCERER', 'WARLOCK', 'WIZARD', name='class_name'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('DRAGONBORN', 'DWARF_HILL', 'DWARF_MOUNTAIN', 'ELF_HIGH', 'ELF_WOOD', 'ELF_DARK', 'GNOME_FOREST', 'GNOME_ROCK', 'HALF_ELF', 'HALF_ORC', 'HALFLING_LIGHTFOOT', 'HALFLING_STOUT', 'HUMAN_STANDARD', 'HUMAN_VARIANT', 'TIEFLING', name='race_name'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('name', sqlmodel.AutoString(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_race_id', sa.Integer(), nullable=False),
    sa.Column('character_class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_class_id'], ['character_class.id'], ),
    sa.ForeignKeyConstraint(['character_race_id'], ['character_race.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    op.drop_table('character_race')
    op.drop_table('character_class')
    # ### end Alembic commands ###
