# Generated by Django 5.2.4 on 2025-09-02 15:53

import app.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_class', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.character.character_image_path)),
                ('hit_points', models.IntegerField()),
                ('armor_class', models.IntegerField()),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('arcana', models.IntegerField(default=0)),
                ('history', models.IntegerField(default=0)),
                ('insight', models.IntegerField(default=0)),
                ('investigation', models.IntegerField(default=0)),
                ('nature', models.IntegerField(default=0)),
                ('perception', models.IntegerField(default=0)),
                ('religion', models.IntegerField(default=0)),
                ('sleight_of_hand', models.IntegerField(default=0)),
                ('stealth', models.IntegerField(default=0)),
            ],
        ),
    ]
